### ISSUE TITLE
Use of Weak SHA-1 to be moved to a stronger Hash

### ISSUE THREAD

**Issue by Abhijith-net** [AppsFlyerSDK/appsflyer-android-sdk#1]
During the security audit of our APP, we found that SHA-1 been used in AppsFlyerSDK.
SHA-1 is a weak hash and need to use a stronger Hash.

**Comment by BenjaminAF** [comment]
Our SDK offers SHA1 hash for user email hashing - it is one option of several:
1.  SHA1
2. SHA256
3. MD5 
The user (developer) can choose which hashing method they want to use.
Please provide the exact code snippet if the issue is elsewhere.

**Comment by af-fess** [comment]
removed in 4.11.0
