### ISSUE TITLE
Exception durging sendTrackingWithEvent

### ISSUE THREAD

**Issue by ybereza** [AppsFlyerSDK/appsflyer-android-sdk#10]
We can not complete installation tracking test after updating to 5.1.0 version. Looks like event can not be sent from device

02-04 17:32:23.262  4273  4382 I AppsFlyer_5.1.0: (00:00:00:215) [Thread-22] ******* sendTrackingWithEvent: Launch
02-04 17:32:23.268  4273  4382 W AppsFlyer_5.1.0: (00:00:00:221) [Thread-22] Exception while collecting facebook's attribution ID. 
02-04 17:32:23.273  4273  4382 I AppsFlyer_5.1.0: (00:00:00:226) [Thread-22] IMEI was not collected.
02-04 17:32:23.274  4273  4382 I AppsFlyer_5.1.0: (00:00:00:227) [Thread-22] Android ID was not collected.
02-04 17:32:23.283  4273  4382 I AppsFlyer_5.1.0: (00:00:00:236) [Thread-22] AppsFlyer: first launch date: 2020-02-04_134241+0000
02-04 17:32:23.283  4273  4382 W AppsFlyer_5.1.0: (00:00:00:236) [Thread-22] Cannot verify existence of our InstanceID Listener Service in the manifest. Please refer to documentation.
02-04 17:32:23.284  4273  4382 D AppsFlyer_5.1.0: (00:00:00:237) [Thread-22] didConfigureTokenRefreshService=false
02-04 17:32:23.284  4273  4382 D AppsFlyer_5.1.0: (00:00:00:237) [Thread-22] No deep link detected
02-04 17:32:23.288  4273  4382 I AppsFlyer_5.1.0: (00:00:00:241) [Thread-22] AppsFlyerLib.sendTrackingWithEvent
02-04 17:32:23.289  4273  4382 V AppsFlyer_5.1.0: (00:00:00:242) [Thread-22] Install referrer will not load, the counter > 2, 

```
02-04 17:32:23.292  4273  4382 I ylab.bloomberr: Rejecting re-init on previously-failed class java.lang.Class<com.appsflyer.internal.a>: java.lang.ExceptionInInitializerError: 
02-04 17:32:23.293  4273  4382 I ylab.bloomberr:   at java.lang.Object com.appsflyer.internal.a.ˏ(int, int, char) (:-1)
02-04 17:32:23.293  4273  4382 I ylab.bloomberr:   at void com.appsflyer.AppsFlyerLibCore$b.run() (:3425)
02-04 17:32:23.293  4273  4382 I ylab.bloomberr:   at void com.appsflyer.AFExecutor$5$3.run() (:31)
```

**Comment by af-vs** [comment]
Hi @ybereza!

If the issue is still relevant, please contact our Support Team with the details above and we will take it from there.

Thank you!
