### ISSUE TITLE
Android Manifest merge error

### ISSUE THREAD

**Issue by shaik41** [AppsFlyerSDK/appsflyer-android-sdk#11]
Hi, 

We ran into manifest merger error for `android:fullBackupContent`

Looked at this closed ticket as well 
https://github.com/AppsFlyerSDK/AppsFlyerAndroidSDK/issues/3

You guys mentioned to add the rule to our backup xml.
```
<full-backup-content>
    ...//your custom rules
    <exclude domain="sharedpref" path="appsflyer-data"/>
</full-backup-content>
```
We did try this but still got the error.
What helped was that we had to use `tools:replace="android:fullBackupContent".`
So If we are right, this replaces the lower priority manifest value (That is Appflyer's Manifest value) with our manifest value which has the extra line which you mentioned to add. 

Is this the right way?

**Comment by imsnow** [comment]
Any news?

**Comment by af-vs** [comment]
Hi!
Apologies for the late reply here. @shaik41 you did exactly right. 

Please refer to the https://github.com/AppsFlyerSDK/appsflyer-android-sdk/issues/9#issuecomment-760150089 for more details, closing those thread in favor of the most active one

Thank you!
