### ISSUE TITLE
I keep getting install referrer alert when testing non-organic installations

### ISSUE THREAD

**Issue by kinejara** [AppsFlyerSDK/appsflyer-android-sdk#14]
I am currently installing the library via gradle, these are the lines I am using:

implementation 'com.appsflyer:af-android-sdk:5.4.1'
implementation 'com.android.installreferrer:installreferrer:2.1'

![Screen Shot 2020-07-16 at 8 47 28 AM](https://user-images.githubusercontent.com/2127397/87683214-69823300-c746-11ea-8a46-aca5a61506e8.png)

**Comment by k4dima** [comment]
add `-keep public class com.android.installreferrer.** { *; }` to proguard rules

**Comment by afdima** [comment]
add `-keep public class com.android.installreferrer.** { *; }` to proguard
