### ISSUE TITLE
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation

### ISSUE THREAD

**Issue by bellol** [AppsFlyerSDK/appsflyer-android-sdk#15]
getting a few of these on the latest version (`5.4.4`)

- Landroid/app/ActivityThread;->currentApplication()Landroid/app/Application;
- Ldalvik/system/BaseDexClassLoader;->pathList:Ldalvik/system/DexPathList;
- Ldalvik/system/DexPathList;->nativeLibraryDirectories:Ljava/util/List;
- Ldalvik/system/DexPathList;->nativeLibraryPathElements:[Ldalvik/system/DexPathList$NativeLibraryElement;

**Comment by af-vs** [comment]
Hi @bellol!

Those warnings are caused by the usage of DexGuard for securing our SDK from reverse engineering. GuardSquare team was contacted regarding those warnings and assured that they keep monitoring that their techniques continue to work with the latest Android releases
