### ISSUE TITLE
Error connection to server: 403

### ISSUE THREAD

**Issue by bhavik-savaliya** [AppsFlyerSDK/appsflyer-android-sdk#16]
Getting response code 403 after integration 

https://gcdsdk.appsflyer.com/install_data/v4.0/com.*****.***********?devkey=**********************&device_id=*************-*******************
AppsFlyer_5.0.0: Calling onConversionFailure with:  Error connection to server: 403

I have re-verified SDK dev key, its correct same as AppsFlyer dashboard.
Please help

**Comment by af-fess** [comment]
please read a response https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/217

> A code 403 means traffic-enabled, meaning zero plan package that used all of its quota


Suggest you contact  support@appsflyer.com
