### ISSUE TITLE
Failed to compile AppsFlyer JAR into an AAR  with R8 on

### ISSUE THREAD

**Issue by JimJayLee** [AppsFlyerSDK/appsflyer-android-sdk#19]
It is easy to reproduce the error. New a module and set `minifyEnabled true`, put the Appsflyer Jar in the _libs_ file and finally add the Proguard rule for keep the AppsFlyer source code, `-keep class com.appsflyer.** { *; }`. Then assemble it to build an AAR. The IDE complain about `com.android.tools.r8.errors.b: Different stack heights at jump target: 0 != 1`. The whole log lists below:

`
11:16:07 AM: Executing task 'assembleRelease'...

Executing tasks: [assembleRelease] in project /Users/macintosh/AndroidStudioProjects/MyApplication2/mylibrary

Starting Gradle Daemon...
Gradle Daemon started in 637 ms
> Task :mylibrary:preBuild UP-TO-DATE
> Task :mylibrary:extractProguardFiles UP-TO-DATE
> Task :mylibrary:preReleaseBuild UP-TO-DATE
> Task :mylibrary:compileReleaseAidl NO-SOURCE
> Task :mylibrary:mergeReleaseJniLibFolders UP-TO-DATE
> Task :mylibrary:mergeReleaseNativeLibs NO-SOURCE
> Task :mylibrary:stripReleaseDebugSymbols NO-SOURCE
> Task :mylibrary:copyReleaseJniLibsProjectAndLocalJars UP-TO-DATE
> Task :mylibrary:compileReleaseRenderscript NO-SOURCE
> Task :mylibrary:generateReleaseBuildConfig UP-TO-DATE
> Task :mylibrary:generateReleaseResValues UP-TO-DATE
> Task :mylibrary:generateReleaseResources UP-TO-DATE
> Task :mylibrary:packageReleaseResources UP-TO-DATE
> Task :mylibrary:parseReleaseLocalResources UP-TO-DATE
> Task :mylibrary:processReleaseManifest UP-TO-DATE
> Task :mylibrary:generateReleaseRFile UP-TO-DATE
> Task :mylibrary:javaPreCompileRelease UP-TO-DATE
> Task :mylibrary:compileReleaseJavaWithJavac UP-TO-DATE
> Task :mylibrary:extractReleaseAnnotations UP-TO-DATE
> Task :mylibrary:mergeReleaseGeneratedProguardFiles UP-TO-DATE
> Task :mylibrary:mergeReleaseConsumerProguardFiles UP-TO-DATE
> Task :mylibrary:mergeReleaseShaders UP-TO-DATE
> Task :mylibrary:compileReleaseShaders NO-SOURCE
> Task :mylibrary:generateReleaseAssets UP-TO-DATE
> Task :mylibrary:packageReleaseAssets UP-TO-DATE
> Task :mylibrary:packageReleaseRenderscript NO-SOURCE
> Task :mylibrary:prepareLintJarForPublish UP-TO-DATE
> Task :mylibrary:generateReleaseLibraryProguardRules UP-TO-DATE
> Task :mylibrary:processReleaseJavaRes NO-SOURCE
> Task :mylibrary:mergeReleaseJavaResource UP-TO-DATE

> Task :mylibrary:minifyReleaseWithR8
AGPBI: {"kind":"warning","text":"Missing class: com.google.firebase.messaging.FirebaseMessagingService","sources":[{}],"tool":"R8"}
AGPBI: {"kind":"warning","text":"Missing class: com.android.installreferrer.api.InstallReferrerStateListener","sources":[{}],"tool":"R8"}
AGPBI: {"kind":"error","text":"com.android.tools.r8.errors.b: Different stack heights at jump target: 0 != 1","sources":[{"file":"/Users/macintosh/AndroidStudioProjects/MyApplication2/mylibrary/libs/af-android-sdk-6.2.3.jar"}],"tool":"R8"}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mylibrary:minifyReleaseWithR8'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/macintosh/AndroidStudioProjects/MyApplication2/mylibrary/libs/af-android-sdk-6.2.3.jar:com/appsflyer/internal/d.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

> Task :mylibrary:minifyReleaseWithR8 FAILED
20 actionable tasks: 1 executed, 19 up-to-date
11:16:16 AM: Task execution finished 'assembleRelease'.
`

By the way, it works well on AppsFlyer AAR using Gradle or Maven, even locally import the AppsFlyer.aar, switch R8 to Proguard or disable obfuscation.

**Comment by af-vs** [comment]
Hi @JimJayLee!

We just recently got exactly the same issue through Customer Success Manager internally and solved it by making sure AppsFlyer SDK is not obfuscated or shrunk. Can please verify that rules are indeed applied?

From the stack trace it looks like despite the proguard rules, the build process still modifies AppsFlyer SDK because the error happens during "mylibrary:minifyReleaseWithR8"

Thank you! 

Closing this for now, but feel free to re-open if that becomes relevant
