### ISSUE TITLE
Unsafe cast to Application prevents AppsFlyerRequestListener notifications

### ISSUE THREAD

**Issue by vlad-kasatkin** [AppsFlyerSDK/appsflyer-android-sdk#20]
Appsflyer version: `com.appsflyer:af-android-sdk:6.2.3`

When using custom application context (used to carry additional services or custom configuration) appsflyer never reports any events to `AppsFlyerRequestListener`. Debug logging shows the following output:

```
                         E  Listener thrown an exception:
                         E  java.lang.ClassCastException: MyCustomContextWrapper cannot be cast to android.app.Application
                         E      at com.appsflyer.internal.ah$3.valueOf(:9053)
                         E      at com.appsflyer.internal.af$5$5.run(:37)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                         E      at java.lang.Thread.run(Thread.java:919)
```

As a result, the [one time opt-out case](https://support.appsflyer.com/hc/en-us/articles/360001422989#onetime-optout) becomes impossible, as there is no way to wait for start to be successful.

Looking through the obfuscated code it seems like that the assumption has been made that any applicationContext of the Activity must be Application, which is violated when `getApplicationContext()` is overriden. 

Steps to reproduce:

1. Create an Activity that overrides `getApplicationContext` and returns a custom `ContextWrapper` impl 
2. Init appsflyer and call start with an implementation of the `AppsFlyerRequestListener`
3. Enable debug logging
4. Launch the app

Expected:
Once appsflyer has been started or failed starting the provided `AppsFlyerRequestListener` should be notified.

Actual:
ClassCastException is thrown and listener is never notified.

Using Appsflyer version: `6.0.0` does not exhibit the same issue

**Comment by af-vs** [comment]
Hi @vlad-kasatkin!

Thanks for reporting this. 

Indeed as of today, in some parts of the SDK we assume that Context is either instance of Activity or Application classes, however, I believe we can fix this issue. We will check this internally and I will update here upon any progress. 

Thanks for your patience!

**Comment by manuel-novoa** [comment]
Any updates on this ticket?
