### ISSUE TITLE
Gradle dependency analasys plugin says that install referrer library is unused

### ISSUE THREAD

**Issue by ColtonIdle** [AppsFlyerSDK/appsflyer-android-sdk#22]
https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin is a very popular plugin that makes sure that your apps dependencies are set up correctly and that you're actually using all of the dependencies that you declare.

If you follow the appsflyer documentation, it says to first add

`implementation 'com.appsflyer:af-android-sdk:6.2.3'`

and then it says to add the play install referrer lib (but most importantly, it leaves out any real information on why/when/where this additional library is required) 

`The Android Install Referrer improves attribution accuracy, protects from install fraud, and more. It is supported from AppsFlyer Android SDK version 4.8.6.`

With that documentation it makes it seem like I should add 

`implementation 'com.android.installreferrer:installreferrer:2.2'`

but after adding both lines, and hooking up appsflyer, the gradle plugin mentioned says that the  second dep is unused and I should remove it and likely that the appsflyers docs are out of date/incorrect.

**Comment by lnk1729** [comment]
Hey! 
Any update on this?
Facing similar issues.

**Comment by ColtonIdle** [comment]
Not stale @lnk1729 @gmeroz @andr-ggn @af-builder
