### ISSUE TITLE
Calling init not from Application onCreate

### ISSUE THREAD

**Issue by slabgames** [AppsFlyerSDK/appsflyer-android-sdk#28]
Is it possible to call init not from Application.onCreate()?

**Comment by af-vs** [comment]
Hi @slabgames 

Sorry for the delayed response. Our main help channel is support@appsflyer.com, you are more likely to get timely assistance there.

As for your question, the answer is yes, however, please make sure to call it before calling start as it is required for some of the SDK functionality.

Thank you!
