### ISSUE TITLE
Not working deeplinks

### ISSUE THREAD

**Issue by AliakseiKasianik** [AppsFlyerSDK/appsflyer-android-sdk#32]
When you start the application for the first time, when you go through deepLink, the application opens and writes in the logs:
AppsFlyer_6.5.0: No deep link detected

When the app is in background, following deepLink does not call subscribeForDeepLink.
A message appears in the logs:
skipping re-use of previously consumed deep link: https://bnine-stage.onelink.me/VwNx/ec137f49 w / af_consumed

More than 30 seconds elapsed between the two launches.

**Comment by af-vs** [comment]
Hi @AliakseiKasianik!

Please open a support ticket at support@appsflyer.com and our team will be more than happy to assist! Please attach full debug logs generated by the SDK and the link that was used

Thank you!
