### ISSUE TITLE
onAppOpenAttribution not being called

### ISSUE THREAD

**Issue by aznj** [AppsFlyerSDK/appsflyer-android-sdk#4]
I don't receive the onAppOpenAttribution when mounting the app for the first time even if I pressed the link. onAppOpenAttribution will not be received whenever app is killed or not exist in the background.
I get a success callback from onInstallConversionData every time opening the app. I can get both callbacks of type onInstallConversionDataLoaded and onAppOpenAttribution.

I called initAppsflyer in onCreate().

How to solve this?

**Comment by witalobenicio** [comment]
Seems like a great support from AppsFlyer. 2021 and no answer.

**Comment by af-vs** [comment]
Hey, we are working on tackling issues on Github, but the main source of getting support from AppsFlyer should be support@appsflyer.com. Our amazing Support Team makes sure to answer every single request.

As for the issue, please provide extra details such as:
1. Version of AppsFlyer SDK
2. If any plugin is being used
3. AppsFlyer logs output when reproducing the issue (use [this API](https://support.appsflyer.com/hc/en-us/articles/207032126-Android-SDK-integration-for-developers#api-reference-setloglevel) to set log level to VERBOSE )
