### ISSUE TITLE
Version 6.10.2 release notes

### ISSUE THREAD

**Issue by cmargonis** [AppsFlyerSDK/appsflyer-android-sdk#49]
Hello, could we please have the release notes for the `6.10.2` version?
We've been checking the release notes [list](https://support.appsflyer.com/hc/en-us/articles/115001256006-AppsFlyer-Android-SDK-release-notes) but it looks like the last notes are of version `6.10.1`.

**Comment by yuvalgnessin-qz** [comment]
@cmargonis if you haven't updated to 6.10.2 yet I suggest that you don't, see #50
