### ISSUE TITLE
Missing settings for backup control for Android 12+

### ISSUE THREAD

**Issue by TomoyaShibata** [AppsFlyerSDK/appsflyer-android-sdk#56]
Hi!

According to the documentation, for Android 12 and above, you need to create a different backup rules file than the one specified in the traditional fullBackupContent attribute and specify it in the dataExtractionRules attribute.
https://developer.android.com/guide/topics/data/autobackup#include-exclude-android-12

AppsFlyer's SDK does not have this implementation.
If it's not what you intended, you'll need to fix it.

**Comment by ColtonIdle** [comment]
I don't think anyone works on this project anymore. Even my similar request went unanswered.

https://github.com/AppsFlyerSDK/appsflyer-android-sdk/issues/36

**Comment by ColtonIdle** [comment]
If anyone is curious how I solved this. My team just started using a different install referrer sdk
