### ISSUE TITLE
AFInAppEventParameterName does not have af_order_id constant

### ISSUE THREAD

**Issue by arnavzoman** [AppsFlyerSDK/appsflyer-android-sdk#6]
One of your recommended event params does not exist in the constants file 

![image](https://user-images.githubusercontent.com/48470219/67919826-f476c980-fbc7-11e9-855e-70f482aed73a.png)

**Comment by af-vs** [comment]
As of today, the latest SDK version 6.2.3 contains af_order_id constant field.

![image](https://user-images.githubusercontent.com/50541317/115690277-91ea2e00-a365-11eb-93fa-7d21baf3e035.png)

Closing as not relevant anymore, thanks!
